=== wishgogo/C/ISPAN/AJAX/website3/emps.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT emps (emp+)>
<!ELEMENT emp (empid,firstname,lastname)>
<!ELEMENT empid (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>

=== wishgogo/C/ISPAN/AJAX/website3/emps2.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/css" href="emps.css"?>
<!DOCTYPE emps SYSTEM "emps.dtd">
<!--<!DOCTYPE emps PUBLIC "-//III//DTD EMPS 1.0//EN" "emps.dtd">-->
<!--以上為prolog區段，以下為body區段 -->
<emps>
  <emp>
    <empid>1</empid>
    <firstname>Nancy</firstname>
    <lastname>Davolio</lastname>    
  </emp>
  <emp>
    <empid>2</empid>
    <firstname>Andrew</firstname>
    <lastname>Fuller</lastname>
  </emp>
  <emp>
    <empid>3</empid>
    <firstname>Janet</firstname>
    <lastname>Leverling</lastname>
  </emp>
</emps>
